softengwebshop2/barket/barket/urls.py
from django.contrib import admin
from django.urls import include, path
from core import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include ('core.urls')),
    path("support/", include ("support.urls"), name="support"),
]

softengwebshop2/barket/core/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomLoginView
from .forms import LoginForm



app_name = "app"
urlpatterns = [
    path('', views.index, name="index"),
    path('products/', views.products, name="products"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.CustomLoginView.as_view(redirect_authenticated_user=True, template_name='core/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.success, name='success'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('about/', views.about, name='about'),
    path('top_up/', views.top_up, name='top_up'),
    path('top_ups/', views.top_ups, name='top_ups'),
    path('top-ups-admin/', views.top_ups_admin, name='top_ups_admin'),
]

softengwebshop2/barket/support/urls.py
from django.urls import path
from . import views

app_name = "support"
urlpatterns = [
    path('create/', views.create_ticket, name='create_ticket'),
    path('ticket/', views.ticket_list, name='ticket'),
    path('respond/<int:ticket_id>/', views.respond_to_ticket, name='respond_to_ticket'),
    path('resolve/<int:ticket_id>/', views.resolve_ticket, name='resolve_ticket')

]

softengwebshop2/barket/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm 
from .models import Contact, TopUpCode
from django.forms import ModelForm
from .models import Ticket, Message
from .models import TopUpCode

class RegisterForm(UserCreationForm):
   
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']
        
class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['subject']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']

class TopUpCodeForm(forms.Form):
    ref_code = forms.CharField(max_length=12, widget=forms.TextInput(attrs={'placeholder': 'Enter Top-Up Code'}))

softengwebshop2/barket/core/views.py
from datetime import date
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.views import View
from .forms import RegisterForm, UpdateUserForm,TopUpCodeForm
from django.contrib.auth.views import LoginView
from .forms import RegisterForm, LoginForm, ContactForm
from django.contrib.auth.decorators import login_required
from .models import Product, CartItem, Order, TopUpCode, TopUpTransaction
from django.http import HttpResponse,Http404	
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.views.decorators.cache import never_cache
from django.utils import timezone
import core.signals
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test


# Create your views here.

def index(request):
    context = {}
    return render(request, 'core/index.html', context)

def products(request):
    context = Product.objects.all()
    
    return render(request, 'core/products.html', {'products': context})

@never_cache
def view_cart(request):
    context = {}
    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user)
        total_price = sum(item.product.price * item.quantity for item in cart_items)
        return render(request, 'core/cart.html', {'cart_items': cart_items, 'total_price': total_price})
    else:
        return render(request, 'core/index.html', context)

def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart_item, created = CartItem.objects.get_or_create(product=product, 
                                                       user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('app:view_cart')
 
def remove_from_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('app:view_cart')

def checkout(request):
    cart_items = CartItem.objects.filter(user=request.user)
    for item in cart_items:
        new_order = Order.objects.create(user=request.user, product=item.product)
        new_order.date_ordered = date.today()
        new_order.quantity = item.quantity
        new_order.save()
    cart_items.delete()
    return redirect('app:orders')

def orders(request):
    context = {}
    if request.user.is_authenticated:
        if request.user.is_staff:
            orders = Order.objects.all()
            return render(request, 'core/orders.html', {'order': orders})
        context = {"order": Order.objects.filter(user=request.user, date_ordered=date.today())}
        return render(request, 'core/orders.html', context)
    else:
        return render(request, 'core/index.html', context)



class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'core/register.html'
    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            return redirect(to='/')
        return render(request, self.template_name, {'form': form})

class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)
    
@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='/profile')
    else:
        user_form = UpdateUserForm(instance=request.user)


    return render(request, 'core/profile.html', {'user_form': user_form})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:success')
    else:
        form = ContactForm()
    return render(request, 'core/contact.html', {'form': form})

def success(request):
    return HttpResponse('Success! Thank you for your message.')

def about(request):
    return render(request, 'core/about.html')


@login_required
def top_up(request):
    if request.method == 'POST':
        form = TopUpCodeForm(request.POST)
        if form.is_valid():
            top_up_code = form.cleaned_data['ref_code']
            try:
                code_obj = TopUpCode.objects.get(ref_code=top_up_code)

                if code_obj.is_used:
                    messages.error(request, 'This top-up code has already been used.')
                elif code_obj.exp_date < timezone.now():
                    messages.error(request, 'This top-up code has expired.')
                else:
                    # Update user's balance and mark the code as used
                    request.user.profile.balance += code_obj.amount
                    request.user.profile.save()
                    code_obj.is_used = True
                    code_obj.save()

                    # Create a top-up transaction record
                    TopUpTransaction.objects.create(user=request.user, top_up_code=code_obj)

                    messages.success(request, f'Successfully topped up {code_obj.amount}!')
                    return redirect('app:profile')

            except TopUpCode.DoesNotExist:
                messages.error(request, 'Invalid top-up code.')
            except Exception as e:
                messages.error(request, f'An unexpected error occurred: {e}')

    else:
        form = TopUpCodeForm()

    return render(request, 'core/top_up.html', {'form': form})

@login_required
def top_ups(request):
    top_ups_list = TopUpTransaction.objects.filter(user=request.user).order_by('-timestamp')
    return render(request, 'core/top_ups.html', {'top_ups_list': top_ups_list})

def is_admin(user):
    return user.is_authenticated and user.is_staff

@user_passes_test(is_admin)
def top_ups_admin(request):
    applied_top_ups = TopUpTransaction.objects.filter(top_up_code__is_used=True).order_by('-timestamp')
    available_top_ups = TopUpCode.objects.filter(is_used=False).order_by('exp_date')

    return render(request, 'core/top_ups_admin.html', {
        'applied_top_ups': applied_top_ups,
        'available_top_ups': available_top_ups,
    })

softengwebshop2/barket/core/templates/core/about.html
{% extends 'core/base.html' %}
{% block content %}
{% load static %}
<div class="products_header"><h2>About Us</h2></div>
<hr>
<div class="about">

    <div class="welcome">
        <img src="{% static 'app/images/about.svg' %}" width="300" height="250">
        <div style="padding: 50px;">
            Welcome to Barket, your online destination for all things pets! <br> At Barket, we believe that every pet deserves the best care, love, and attention.  <br>That's why we've created an online store that caters to all the needs of your furry friends.
        </div>
    </div>

    <hr>

    <div class="about_us">
        <div style="padding: 20px;">
            <div style="text-align:center;"><h3>Our Mission</h3></div>
            <p>Barket was founded with a clear mission - to provide pets and their owners with the highest quality products along with top-notch service. <br> Our passion for pets inspires us to constantly seek the latest and most innovative products <br> on the market to ensure the happiness and well-being of every member of your family.</p>
        </div>
     
        <div style="padding: 20px;">
            <div style="text-align:center;"><h3>What Sets Us Apart?</h3></div>
            <p><strong>Wide Range of Products:</strong> Barket offers a diverse range of products for dogs, cats, birds, small mammals, fish, and reptiles.  <br> Whether you're looking for high-quality food, comfortable beds, toys that encourage play, or various other products, we have everything your pet needs.<br>
                <strong>Quality:</strong> All our products are carefully selected to ensure top-notch quality.  <br>We collaborate with reputable brands that share our commitment to the health and happiness of pets. <br>   
                <strong>Fast Delivery:</strong> We understand that you want to receive your pet products quickly.  <br>That's why we work with reliable delivery partners to ensure fast and secure delivery to your doorstep.</p>
        </div>
        <div style="padding: 20px;">
            <div style="text-align:center;"><h3>Our Team</h3></div>
            <p>Barket is comprised of passionate animal lovers and experts dedicated to providing the best products and advice. . <br>Our team is always available to answer your questions and provide support.</p>
        </div>

    </div>

    <hr>

    <div class="welcome">
        <div style="padding: 50px;">
            We want to express our gratitude to all our customers who entrust us with the care of their pets.  <br>Your trust is the foundation of our success, and we look forward to continuing our collaboration to create happy moments with your pets.<br>  
            Welcome to Barket - where the love for pets becomes even more beautiful with quality products and service!</p>
        </div>
        <img src="{% static 'app/images/pets.svg' %}" width="300" height="250">
    </div>

</div>


{% endblock content %}

softengwebshop2/barket/core/templates/core/base.html
{% load static %}
<html>
  <head>
    <title>Barket</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">
            <img src="{% static 'app/images/icon.svg' %}" width="30" height="30" alt="">
          </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li {% if request.resolver_match.url_name == 'index' %} class="nav-item active ml-2 mr-3" {% endif %} class="nav-item ml-2 mr-3">
                    <a class="nav-link" href="/">HOME<span class="sr-only">(current)</span></a>
                </li>
                <li {% if request.resolver_match.url_name == 'products' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3"> 
                    <a class="nav-link" href="{% url 'app:products' %}">PRODUCTS</a>
                </li>
                <li {% if request.resolver_match.url_name == 'about' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'app:about' %}">ABOUT US</a>
                </li>
                <li {% if request.resolver_match.url_name == 'contact' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'app:contact' %}">CONTACT US</a>
                </li>
                <li {% if request.resolver_match.url_name == 'ticket' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3">
                  {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'support:ticket' %}">TICKETS</a>
                  {% endif %}
              </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'app:profile' %}"><img src="{% static 'app/images/user.svg' %}" width="30" height="30" alt=""></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:logout' %}?next="> LOG OUT</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:top_ups' %}"> TOP UPS</a>
                </li>
                <li class="nav-item">
                  {% if request.user.is_superuser %}
                  <a class="nav-link" href="/admin">ADMIN DASHBOARD</a>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:top_ups_admin' %}">ALL TOP UPS</a>
                </li>
                  {% else %}
                  <a class="nav-link" href="{% url 'app:orders' %}">ORDERS</a>
                  
                  {% endif %}
                </li>
               
                <li class="nav-item">
                  {% else %}
                    <a class="nav-link" href="{% url 'app:register' %}">REGISTER</a>
                   
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:login' %}">LOG IN</a>
                  {% endif %}
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:view_cart' %}"><img src="{% static 'app/images/cart.svg' %}" width="30" height="30" alt=""></a>
                </li>
            </ul>
        </div>
      </nav>
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}
        {% endblock content %}
        <div class="">
            <footer class="d-flex flex-wrap justify-content-between align-items-center border-top">
              <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <img src="{% static 'app/images/icon.svg' %}" width="30" height="30" alt="">
                </a>
                <span id="logo_text" class="mb-3 ml-2 mb-md-0">Barket</span>
                <span id="quote" class="mb-3 ml-5 mb-md-0">One bark is all it takes to make your pet’s tail wag!</span>
              </div>
              <img src="{% static 'app/images/footer_image.svg' %}" width="200" height="60" alt="">
              <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3 mr-3"><a class="text-muted" href="#"><img src="{% static 'app/images/facebook.svg' %}" width="30" height="30" alt=""></a></li>
                <li class="ms-3 mr-3"><a class="text-muted" href="#"><img src="{% static 'app/images/twitter.svg' %}" width="30" height="30" alt=""></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'app/images/instagram.svg' %}" width="30" height="30" alt=""></a></li>
              </ul>
            </footer>
          </div>
  </body>
</html>

softengwebshop2/barket/core/templates/core/cart.html
{% extends 'core/base.html' %}
{% block title %} Cart {% endblock title %}
{% load static %}
{% block content %}
<div class="products_header"><h2>Cart</h2></div>
<hr>
<div class="products">
    {% for item in cart_items %}
    <div class="product">
        <div class="product_image">
            <img src="{{ item.product.image }}" alt="" class="dogFoodImg">
        </div>
        <div class="product_info">
            <h3>{{ item.product.name }}</h3>
            <p>{{ item.product.description }}</p>
            <div class="">
                <p>Price: {{ item.product.price }} $</p>
            </div>
            <div class="cart-items">
                <p>Quantity: {{ item.quantity }}</p>
                <a href="{% url 'app:remove_from_cart' item.id %}"><button type="button" class="btn btn-primary border-0" style="background-color:#07d226;border-radius: 25px; width: 100px; margin-bottom: 5px;">Remove</button></a>
            </div>
        </div>
    </div>
    {% empty %}
    <p>Your cart is empty.</p>
    {% endfor %}
</div>
<div class="products">
    {% if cart_items %}
    <a href="{% url 'app:products' %}"><button type="button" class="btn btn-primary border-0 mb-5 mr-2" style="background-color:#07d226;border-radius: 25px; padding: 2.5%;width: 150px;">Continue Shopping</button></a>
    <a href="{% url 'app:checkout' %}"><button type="button" class="btn btn-primary border-0 mb-5 ml-2" style="background-color:#07d226;border-radius: 25px; padding: 2.5%;width: 150px;">Checkout</button></a>
    {% else %}
    <a href="{% url 'app:products' %}"><button type="button" class="btn btn-primary border-0 mb-5 mr-2" style="background-color:#07d226;border-radius: 25px; padding: 2.5%;width: 150px;">Continue Shopping</button></a>
    {% endif %}
</div>
<div class="products">
    <p>Total: ${{ total_price }}</p>
</div>
{% endblock content %}

softengwebshop2/barket/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block content %}
{% load static %}
<div class="index_welcome">
    <div class="index_text">
        <h2>Get Goods for Your Furry Friend</h2>
        <h5>Find the Finest Pet Supplies at Your Fingertips</h5>
        <a class="nav-link" href="{% url 'app:products' %}"><button type="button" class="btn btn-primary border-0 mt-5" style="background-color:#07d226;border-radius: 25px; padding: 2.5%;width: 150px;">Products</button></a>
    </div>
    <img src="{% static 'app/images/dog_image.svg' %}" width="400" height="500" alt="">

    <a class="nav-link" href="{% url 'app:top_up' %}"><button type="button" class="btn btn-primary border-0 mt-5" style="background-color:#07d226;border-radius: 25px; padding: 2.5%;width: 150px;">Top-Up Balance</button></a>
    </div>

</div>  
{% endblock content %}

softengwebshop2/barket/core/templates/core/logout.html
{% extends 'core/base.html' %}
{% block title %}Logout{% endblock title %}
{% load static %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>

        </div>
    </div>
    <script>
        setTimeout(function() {
            window.location.href = "{% url 'app:index' %}";
        }, 100);
    </script>

{% endblock content %}

softengwebshop2/barket/core/templates/core/orders.html
{% extends 'core/base.html' %}
{% block title %} Orders {% endblock title %}
{% load static %}
{% block content %}
<div class="products_header"><h2>Orders</h2></div>
<hr>
<div class="products">
    {% for item in order %}
    <div class="product">
        <div class="product_image">
            <img src="{{ item.product.image }}" alt="" class="dogFoodImg">
        </div>
        <div class="product_info">
            {% if request.user.is_staff %}
               <p><strong>{{ item.user.username }}</strong></p>
            {% endif %}
            <h3>{{ item.product.name }}</h3>
            <p>{{ item.product.description }}</p>
            <div class="">
                <p>Price: {{ item.product.price }} $</p>
            </div>
            <div class="cart-items">
                <p>Quantity: {{ item.quantity }}</p>
            </div>
        </div>
    </div>
    {% empty %}
    <p>You don't have any orders.</p>
    {% endfor %}
</div>
{% endblock content %}

softengwebshop2/barket/core/templates/core/products.html
{% extends 'core/base.html' %}
{% block title %}Products{% endblock title %}
{% block content %}
{% load static %}
<div class="products_header"><h2>Products</h2></div>
<hr>
<div class="products">
    {% for product in products %}
    <div class="product">
        <div class="product_image">
            <img src="{{ product.image }}" alt="" class="dogFoodImg">
        </div>
        <div class="product_info">
            <h3>{{ product.name }}</h3>
            <p>{{ product.description }}</p>
            <div class="price_info">
                <p>{{ product.price }} $</p>
                {% if user.is_authenticated %}
                <a href="{% url 'app:add_to_cart' product.id %}" ><button type="button" class="btn btn-primary border-0" style="background-color:#07d226;border-radius: 25px;width: 150px;">Add to Cart</button></a>
                {% else %}
                <a href="{% url 'app:login' %}"><button type="button" class="btn btn-primary border-0" style="background-color:#07d226;border-radius: 25px;width: 150px;">Login to buy</button></a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock content %}

softengwebshop2/barket/core/templates/core/top_up.html
{% extends 'core/base.html' %}

{% block content %}
    <h2>Top-Up Your Balance</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Top Up</button>
    </form>
{% endblock %}