softengwebshop2/barket/barket/urls.py
from django.contrib import admin
from django.urls import include, path
from core import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include ('core.urls')),
    path("support/", include ("support.urls"), name="support"),
]

softengwebshop2/barket/core/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomLoginView
from .forms import LoginForm



app_name = "app"
urlpatterns = [
    path('', views.index, name="index"),
    path('products/', views.products, name="products"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.CustomLoginView.as_view(redirect_authenticated_user=True, template_name='core/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.success, name='success'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('about/', views.about, name='about'),
    path('top_up/', views.top_up, name='top_up'),
    path('top_ups/', views.top_ups, name='top_ups'),
    path('top-ups-admin/', views.top_ups_admin, name='top_ups_admin'),
]

softengwebshop2/barket/support/urls.py
from django.urls import path
from . import views

app_name = "support"
urlpatterns = [
    path('create/', views.create_ticket, name='create_ticket'),
    path('ticket/', views.ticket_list, name='ticket'),
    path('respond/<int:ticket_id>/', views.respond_to_ticket, name='respond_to_ticket'),
    path('resolve/<int:ticket_id>/', views.resolve_ticket, name='resolve_ticket')

]

softengwebshop2/barket/support/models.py
from django.db import models

# Create your models here.

softengwebshop2/barket/support/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from core.models import Ticket
from django.contrib.auth.models import User
from django.contrib import messages
from core.models import Ticket, Message
from core.forms import TicketForm, MessageForm

# Create your views here.

@login_required
def create_ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            messages.success(request, 'Ticket created successfully!')
            return redirect('support:ticket')
    else:
        form = TicketForm()

    return render(request, 'support/create_ticket.html', {'form': form})


@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(user=request.user)
    if request.user.is_staff:
        tickets = Ticket.objects.all()
    return render(request, 'support/ticket.html', {'tickets': tickets})

@login_required
def respond_to_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)
    messages_for_ticket = Message.objects.filter(ticket=ticket)
    
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.ticket = ticket
            message.user = request.user
            message.save()
            messages.success(request, 'Message sent successfully!')
            return redirect('support:respond_to_ticket', ticket_id=ticket_id)
    else:
        form = MessageForm()

    return render(request, 'support/respond_to_ticket.html', {'ticket': ticket, 'form': form, 'ticket_messages': messages_for_ticket})

@login_required
def resolve_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)
    ticket.is_resolved = True
    ticket.save()
    messages.success(request, 'Ticket resolved successfully!')
    return redirect('support:ticket')

softengwebshop2/barket/support/templates/support/base.html
{% load static %}
<html>
  <head>
    <title>Barket</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">
            <img src="{% static 'app/images/icon.svg' %}" width="30" height="30" alt="">
          </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li {% if request.resolver_match.url_name == 'index' %} class="nav-item active ml-2 mr-3" {% endif %} class="nav-item ml-2 mr-3">
                    <a class="nav-link" href="/">HOME<span class="sr-only">(current)</span></a>
                </li>
                <li {% if request.resolver_match.url_name == 'products' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3"> 
                    <a class="nav-link" href="{% url 'app:products' %}">PRODUCTS</a>
                </li>
                <li {% if request.resolver_match.url_name == 'about' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'app:about' %}">ABOUT US</a>
                </li>
                <li {% if request.resolver_match.url_name == 'contact' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'app:contact' %}">CONTACT US</a>
                </li>
                <li {% if request.resolver_match.url_name == 'ticket' %} class="nav-item active mr-3" {% endif %} class="nav-item mr-3">
                  {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'support:ticket' %}">TICKETS</a>
                  {% endif %}
              </li>
              
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'app:profile' %}"><img src="{% static 'app/images/user.svg' %}" width="30" height="30" alt=""></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:logout' %}?next="> LOG OUT</a>

                </li>
                <li class="nav-item">
                  {% if request.user.is_superuser %}
                  <a class="nav-link" href="/admin">ADMIN DASHBOARD</a>
                  {% else %}
                  <a class="nav-link" href="{% url 'app:orders' %}">ORDERS</a>
                  {% endif %}
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:top_ups' %}"> TOP UPS</a>
                </li>
                <li class="nav-item">
                  {% else %}
                    <a class="nav-link" href="{% url 'app:register' %}">REGISTER</a>
                   
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:login' %}">LOG IN</a>
                  {% endif %}
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:view_cart' %}"><img src="{% static 'app/images/cart.svg' %}" width="30" height="30" alt=""></a>
                </li>
            </ul>
        </div>
      </nav>
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}
        {% endblock content %}
        <div class="">
            <footer class="d-flex flex-wrap justify-content-between align-items-center border-top">
              <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <img src="{% static 'app/images/icon.svg' %}" width="30" height="30" alt="">
                </a>
                <span id="logo_text" class="mb-3 ml-2 mb-md-0">Barket</span>
                <span id="quote" class="mb-3 ml-5 mb-md-0">One bark is all it takes to make your pet’s tail wag!</span>
              </div>
              <img src="{% static 'app/images/footer_image.svg' %}" width="200" height="60" alt="">
              <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3 mr-3"><a class="text-muted" href="#"><img src="{% static 'app/images/facebook.svg' %}" width="30" height="30" alt=""></a></li>
                <li class="ms-3 mr-3"><a class="text-muted" href="#"><img src="{% static 'app/images/twitter.svg' %}" width="30" height="30" alt=""></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'app/images/instagram.svg' %}" width="30" height="30" alt=""></a></li>
              </ul>
            </footer>
          </div>
  </body>
</html>

softengwebshop2/barket/support/templates/support/create_ticket.html
<!-- create_ticket.html -->
{% extends 'support/base.html' %}

{% block content %}

  <div class="products_header"><h2>Create a Ticket</h2></div><hr>
  <center>
  <form method="post">
    {% csrf_token %}
    <div class="product">
        <label for="name"><strong>Subject:</strong></label>
        {{ form.subject }}
        <br>
        <button type="submit" class="btn btn-primary border-0 mt-2" style="background-color:#07d226;border-radius: 25px; ;width: 100%;">Submit Ticket</button>
    </div>
  </form>
</center>
  
{% endblock %}

softengwebshop2/barket/support/templates/support/respond_to_ticket.html
{% extends 'support/base.html' %}

{% load static %}

{% block content %}
<div class="products_header"><h2>Respond To Ticket</h2></div><hr>
  <div class="products_header"><h3>Subject: <small>{{ ticket.subject }}</small></h3></div>

  
    {% for message in ticket_messages %}

        {% if message.user == ticket.user %}
        <div class="box">
          <div class="center">
            {% if request.user.is_staff %}
            <div class="dialog1">
              <div class="left-point"></div>
              {% else %}
              <div class="dialog2">
                <div class="right-point"></div>
                {% endif %}
                    <div class="msg_container">
                      <div class="from"><strong id="user">{{ message.user }}</strong></div>
                      <div class="msg_content"> {{ message.content }}</div>
                      <div class="msg_time">{{ message.timestamp }}</div> 
                  </div>
              </div>
          </div>
        </div>
        {% else %}
        <div class="box">
          <div class="center">
            {% if request.user.is_staff %}
            <div class="dialog2">
              <div class="right-point"></div>
              {% else %}
              <div class = "dialog1">
                <div class="left-point"></div>
                {% endif %}
                <div class="msg_container">
                  <div class="from"><strong id="user">Support</strong></div>
                  <div class="msg_content"> {{ message.content }}</div>
                  <div class="msg_time">{{ message.timestamp }}</div>
                </div>
            </div>
          </div>
        </div>
        {% endif %}

    {% endfor %}
  

  {% if not ticket.is_resolved %}
    <form method="post">
      {% csrf_token %}
      <div class="msg_form">
        <label for="content"><strong>Message:</strong></label>
        {{ form.content }}
        <div>
          <button type="submit" class="btn btn-primary border-0 mt-2" style="background-color:#07d226;border-radius: 25px; ;width: 100%;">Send Message</button>
          </form>
          {% if request.user.is_staff %}
              <a href="{% url 'support:resolve_ticket' ticket.id %}"><button type="button" class="btn btn-primary border-0 mt-2" style="background-color:#07d226;border-radius: 25px; width: 100%;">Resolve Ticket</button></a>
          {% endif %}
      </div>
      </div>
      
  {% endif %}

{% endblock %}

softengwebshop2/barket/support/templates/support/ticket.html
{% extends 'support/base.html' %}
{% block content %}
{% load static %}
<div class="products_header"><h2>Tickets</h2></div>
<hr><center>
<div class="">
    <div class="product">
        {% if request.user.is_staff %}
        <h2>Support Ticket List</h2>
        {% for ticket in tickets %}
            <a href="{% url 'support:respond_to_ticket' ticket.id %}"><p>{{ ticket.subject }} - {{ ticket.user.username }} - {% if ticket.is_resolved %}Resolved{% else %}Open{% endif %}</p></a>
            {% empty %}
            <p>No tickets found</p>
        {% endfor %}
        {% else %}
        <h2>Your Tickets</h2>
        {% for ticket in tickets %}
          <a href="{% url 'support:respond_to_ticket' ticket.id%}"><p>{{ ticket.subject }} - {{ ticket.created_at }} - {% if ticket.is_resolved %}Resolved{% else %}Open{% endif %}</p></a>
          {% empty %}
            <p>No tickets found</p>
        {% endfor %}
        {% endif %}
        {% if not request.user.is_staff %}
        <a class="nav-link" href="{% url 'support:create_ticket' %}"><button type="button" class="btn btn-primary border-0 mt-5" style="background-color:#07d226;border-radius: 25px; padding: 2.5%;width: 150px;">Create a ticket</button></a> 
        {% endif %}
    </div>
   
</div>
</center>
{% endblock content %}